### ISSUE TITLE
API missing nextRecordPosition in Loop with more than 100 records

### ISSUE THREAD

**Issue by StefanMunnes** [chgrl/rdnb#2]
Hey,
thanks for this nice package.  Since recently I have an error when I want to process requests with more than 100 records: 

`dnb_advanced("atr='Bronsky, Alina'", limit = "all", clean = T)`

But I think I know where the problem comes from. Apparently the API does not return a valid number (`raw[["nextRecordPosition"]]`) in the last loop. So I just added the following condition in the beginning of the repeat loop in line 225/226 in the gets.R file: `if(is_empty(strt)) break` 
Than it works again.

**Comment by chgrl** [comment]
Thanks Stefan, I just fixed it. New version is on it's way to CRAN...
